/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package andresmartinez_javaticket;

import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class CrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public CrearUsuario() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreCompleto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        botonAdmin = new javax.swing.JButton();
        botonContenido = new javax.swing.JButton();
        botonLimitado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Crear Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 240, 60));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Edad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 60, 30));

        nombreCompleto.setBackground(new java.awt.Color(255, 255, 255));
        nombreCompleto.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(nombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 200, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Tipo de Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 160, 30));

        user.setBackground(new java.awt.Color(255, 255, 255));
        user.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 200, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 80, 30));

        pass.setBackground(new java.awt.Color(255, 255, 255));
        pass.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 200, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 110, 30));

        edad.setBackground(new java.awt.Color(255, 255, 255));
        edad.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 200, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 204, 255));
        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 190, 50));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 204));
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 140, 50));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Nombre Completo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 160, 30));

        botonAdmin.setBackground(new java.awt.Color(0, 153, 0));
        botonAdmin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        botonAdmin.setForeground(new java.awt.Color(204, 255, 204));
        botonAdmin.setText("Administrador");
        botonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminActionPerformed(evt);
            }
        });
        jPanel1.add(botonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 130, 30));

        botonContenido.setBackground(new java.awt.Color(0, 153, 0));
        botonContenido.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        botonContenido.setForeground(new java.awt.Color(204, 255, 204));
        botonContenido.setText("Contenido");
        botonContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContenidoActionPerformed(evt);
            }
        });
        jPanel1.add(botonContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 100, 30));

        botonLimitado.setBackground(new java.awt.Color(0, 153, 0));
        botonLimitado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        botonLimitado.setForeground(new java.awt.Color(204, 255, 204));
        botonLimitado.setText("Limitado");
        botonLimitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimitadoActionPerformed(evt);
            }
        });
        jPanel1.add(botonLimitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int contador=0,edadT;
    String tipoDeDatos="";
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdministracionUsuarios admin = new AdministracionUsuarios();
        admin.setVisible(true);
        admin.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Usuarios users = new Admin(user.getText(),pass.getText());
        if(contador==0){
            JOptionPane.showMessageDialog(this, "Seleccionar tipo de Usuario! ");
        }
        
        
        if(user.getText().isEmpty() || nombreCompleto.getText().isEmpty() || pass.getText().isEmpty() || edad.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Favor rellenar todas las casillas! ");
        }else if(users.buscar(user.getText(),0)!= -1){
            JOptionPane.showMessageDialog(this, "Este usuario ya existe! ");
        }else{
            edadT=Integer.parseInt(edad.getText());
            JOptionPane.showMessageDialog(this, "Usuario creado correctamente! ");
            Usuarios.usernames.add(users);
            int posicion=users.buscar(user.getText(),0);
            if(tipoDeDatos.equals("admin")){
                Usuarios.usernames.get(posicion).setAcceso("admin");
            }else if(tipoDeDatos.equals("contenido")){
                Usuarios.usernames.get(posicion).setAcceso("contenido");
            }else{
                Usuarios.usernames.get(posicion).setAcceso("limitado");
            }
            user.setText("");
            nombreCompleto.setText("");
            pass.setText("");
            edad.setText("");
            contador=0;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminActionPerformed
       tipoDeDatos="admin";
        contador++;
    }//GEN-LAST:event_botonAdminActionPerformed

    private void botonContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContenidoActionPerformed
        tipoDeDatos="contenido";
        contador++;
    }//GEN-LAST:event_botonContenidoActionPerformed

    private void botonLimitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimitadoActionPerformed
        tipoDeDatos="limmitado";
        contador++;
    }//GEN-LAST:event_botonLimitadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdmin;
    private javax.swing.JButton botonContenido;
    private javax.swing.JButton botonLimitado;
    private javax.swing.JTextField edad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreCompleto;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
