/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package andresmartinez_javaticket;

/**
 *
 * @author andre
 */
import javax.swing.JOptionPane;
import java.util.Calendar;
public class crearEvento extends javax.swing.JFrame {

    /**
     * Creates new form crearEvento
     */
    public crearEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codigoT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        eventoT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        descripcionT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        montoT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        botonD = new javax.swing.JButton();
        botonM = new javax.swing.JButton();
        botonR = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        calendario = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        cantPersonas = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Crear Evento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 220, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Monto de Renta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 190, 40));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Tipo de Evento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, 40));

        codigoT.setBackground(new java.awt.Color(255, 255, 255));
        codigoT.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        codigoT.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(codigoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 210, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Fecha");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 90, 40));

        eventoT.setBackground(new java.awt.Color(255, 255, 255));
        eventoT.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eventoT.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(eventoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 210, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Titulo del Evento");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 190, 40));

        descripcionT.setBackground(new java.awt.Color(255, 255, 255));
        descripcionT.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        descripcionT.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(descripcionT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 340, 30));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Descripcion de Evento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 260, 40));

        montoT.setBackground(new java.awt.Color(255, 255, 255));
        montoT.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        montoT.setForeground(new java.awt.Color(0, 0, 0));
        montoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoTActionPerformed(evt);
            }
        });
        jPanel1.add(montoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 260, 30));

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 255, 153));
        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 220, 60));

        botonD.setBackground(new java.awt.Color(0, 153, 0));
        botonD.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        botonD.setForeground(new java.awt.Color(153, 255, 153));
        botonD.setText("Deportivo");
        botonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDActionPerformed(evt);
            }
        });
        jPanel1.add(botonD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, 40));

        botonM.setBackground(new java.awt.Color(0, 153, 0));
        botonM.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        botonM.setForeground(new java.awt.Color(153, 255, 153));
        botonM.setText("Musical");
        botonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMActionPerformed(evt);
            }
        });
        jPanel1.add(botonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 90, 40));

        botonR.setBackground(new java.awt.Color(0, 153, 0));
        botonR.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        botonR.setForeground(new java.awt.Color(153, 255, 153));
        botonR.setText("Religioso");
        botonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRActionPerformed(evt);
            }
        });
        jPanel1.add(botonR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 120, 40));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Cantidad de Personas");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 240, 40));
        jPanel1.add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 170, 40));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Codigo Unico");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 170, 40));

        cantPersonas.setBackground(new java.awt.Color(255, 255, 255));
        cantPersonas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        cantPersonas.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cantPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 320, 30));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 220, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void botonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDActionPerformed
        tipoEvento=botonD.getText();
        jLabel2.setVisible(true);
        montoT.setVisible(true);
        contador++;
    }//GEN-LAST:event_botonDActionPerformed

    private void botonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMActionPerformed
        tipoEvento=botonM.getText();
        jLabel2.setVisible(true);
        montoT.setVisible(true);
        contador++;
    }//GEN-LAST:event_botonMActionPerformed
    
    public static int day,month,year,codigoEvent,personas;
    public static String tipoEvento="",titulo="",description="",estado="";
    public static double monto;
    int contador=0;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(Eventos.events);
        if(contador==0){
            JOptionPane.showMessageDialog(this, "Seleccionar tipo de Usuario! ");
        }
        if(codigoT.getText().isEmpty() || eventoT.getText().isEmpty() || descripcionT.getText().isEmpty() || montoT.getText().isEmpty() || calendario.getDate()==null){
            JOptionPane.showMessageDialog(this, "Favor rellenar todas las casillas! ");
        }
        
        codigoEvent=Integer.parseInt(codigoT.getText());
        titulo=eventoT.getText();
        description=descripcionT.getText();
        monto=Double.parseDouble(montoT.getText());
        personas=Integer.parseInt(cantPersonas.getText());
        day = calendario.getCalendar().get(Calendar.DAY_OF_MONTH);
        month = calendario.getCalendar().get(Calendar.MONTH);
        year = calendario.getCalendar().get(Calendar.YEAR);
        estado="pendiente";
        
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.MONTH, month);
        calendar.set(Calendar.DAY_OF_MONTH, day);

        Eventos events = new Eventos(Login.logged,estado,codigoEvent,titulo,description,tipoEvento,monto,calendar,personas);
       
        if(tipoEvento.equalsIgnoreCase("deportivo")){
            if(personas>20000 || personas<0){
                JOptionPane.showMessageDialog(this, "Cantidad de personas invalido! ");
            }else{
                if(events.buscar(codigoEvent,0)!= null){
                    JOptionPane.showMessageDialog(this, "Codigo del evento existente! ");
            }else{
                eventoDeportivo e = new eventoDeportivo();
                e.setVisible(true);
                e.setLocationRelativeTo(null);
                this.setVisible(false);
            }
        }
        }
            
        if(tipoEvento.equalsIgnoreCase("musical")){
            if(personas<0 || personas>25000){
            JOptionPane.showMessageDialog(this, "Cantidad de personas invalido! ");
            }else{
                if(events.buscar(codigoEvent,0)!= null){
                    JOptionPane.showMessageDialog(this, "Codigo del evento existente! ");
            }else{
                monto+=(0.3*monto);
                eventoMusical em = new eventoMusical();
                em.setVisible(true);
                em.setLocationRelativeTo(null);
                this.setVisible(false);
            }
        }
        }
        
        if(tipoEvento.equalsIgnoreCase("religioso")){
            if(personas>30000 || personas<0){
               JOptionPane.showMessageDialog(this, "Cantidad de personas invalido! ");
            }else{
                if(events.buscar(codigoEvent,0)!=null){
                    JOptionPane.showMessageDialog(this, "Codigo del evento existente! ");
                }else{
                    monto+=2000;
                    religioso religios = new religioso(Login.logged,estado,codigoEvent,titulo,description,tipoEvento,monto,calendar,personas);
                    religios.agregarEvento(religios);
                    JOptionPane.showMessageDialog(this, "Evento creado exitosamente! ");
                    AdministracionEventos admin = new AdministracionEventos();
                    admin.setVisible(true);
                    admin.setLocationRelativeTo(null);
                    this.setVisible(false);
                }
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRActionPerformed
       tipoEvento=botonR.getText();
       jLabel2.setVisible(false);
       montoT.setVisible(false);
       montoT.setText("0");
       contador++;
    }//GEN-LAST:event_botonRActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdministracionEventos menu = new AdministracionEventos();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void montoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonD;
    private javax.swing.JButton botonM;
    private javax.swing.JButton botonR;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JTextField cantPersonas;
    private javax.swing.JTextField codigoT;
    private javax.swing.JTextField descripcionT;
    private javax.swing.JTextField eventoT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField montoT;
    // End of variables declaration//GEN-END:variables
}
