/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package andresmartinez_javaticket;

import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class editarEvento extends javax.swing.JFrame {

    /**
     * Creates new form editarEvento
     */
    public editarEvento() {
        initComponents();
        modificacionEventoDeportivo.setVisible(false);
        modificacionEventoMusical.setVisible(false);
        modificacionEventoReligioso.setVisible(false);
        personasConvertidas.setVisible(false);
        bandazzz.setVisible(false);
        equipozzz.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        solicitudCode = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoAEditar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        modificacionEventoReligioso = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        text13 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        text14 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        text15 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        text16 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        datezzz2 = new com.toedter.calendar.JDateChooser();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        modificacionEventoMusical = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        text8 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        text9 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        text10 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        text11 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        datezzz1 = new com.toedter.calendar.JDateChooser();
        jLabel38 = new javax.swing.JLabel();
        text12 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        modificacionEventoDeportivo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        text4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        datezzz = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        text5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        text6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        text7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        bandazzz = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        integrante2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        integrante1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        integrante3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        rol1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        rol2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        rol3 = new javax.swing.JTextField();
        equipozzz = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        j1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        j2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        j3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        j4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        j5 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        j6 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        j7 = new javax.swing.JTextField();
        j8 = new javax.swing.JTextField();
        j9 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        j10 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        personasConvertidas = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        solicitudCode.setBackground(new java.awt.Color(153, 255, 255));
        solicitudCode.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Codigo del Evento");
        solicitudCode.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 310, 50));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Editar Evento");
        solicitudCode.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 330, 100));

        codigoAEditar.setBackground(new java.awt.Color(255, 255, 255));
        codigoAEditar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        codigoAEditar.setForeground(new java.awt.Color(0, 0, 0));
        solicitudCode.add(codigoAEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 210, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        solicitudCode.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 220, 100));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 204));
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        solicitudCode.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 230, 100));

        getContentPane().add(solicitudCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 530));

        modificacionEventoReligioso.setBackground(new java.awt.Color(153, 255, 255));
        modificacionEventoReligioso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 102));
        jLabel40.setText("Modificar Evento Musical");
        modificacionEventoReligioso.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 460, 60));

        jLabel41.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 102));
        jLabel41.setText("Cantidad de Personas");
        modificacionEventoReligioso.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 250, 60));

        text13.setBackground(new java.awt.Color(255, 255, 255));
        text13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text13.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoReligioso.add(text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 240, 30));

        jLabel42.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 102));
        jLabel42.setText("Codigo unico");
        modificacionEventoReligioso.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 60));

        text14.setBackground(new java.awt.Color(255, 255, 255));
        text14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text14.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoReligioso.add(text14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 220, 30));

        jLabel43.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 102));
        jLabel43.setText("Titulo");
        modificacionEventoReligioso.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 70, 60));

        text15.setBackground(new java.awt.Color(255, 255, 255));
        text15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text15.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoReligioso.add(text15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 200, 30));

        jLabel44.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 102));
        jLabel44.setText("Descripcion");
        modificacionEventoReligioso.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 60));

        text16.setBackground(new java.awt.Color(255, 255, 255));
        text16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text16.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoReligioso.add(text16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 210, 30));

        jLabel45.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 102));
        jLabel45.setText("Fecha");
        modificacionEventoReligioso.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 70, 60));
        modificacionEventoReligioso.add(datezzz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 210, 40));

        jButton10.setBackground(new java.awt.Color(0, 0, 102));
        jButton10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(153, 255, 255));
        jButton10.setText("Siguiente");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        modificacionEventoReligioso.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 210, 80));

        jButton11.setBackground(new java.awt.Color(102, 0, 0));
        jButton11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 153, 153));
        jButton11.setText("Regresar al menu");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        modificacionEventoReligioso.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 210, 80));

        getContentPane().add(modificacionEventoReligioso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 450));

        modificacionEventoMusical.setBackground(new java.awt.Color(153, 255, 255));
        modificacionEventoMusical.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 102));
        jLabel32.setText("Modificar Evento Musical");
        modificacionEventoMusical.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 460, 60));

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 102));
        jLabel33.setText("Cantidad de Personas");
        modificacionEventoMusical.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 250, 60));

        text8.setBackground(new java.awt.Color(255, 255, 255));
        text8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text8.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoMusical.add(text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 240, 30));

        jLabel34.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 102));
        jLabel34.setText("Codigo unico");
        modificacionEventoMusical.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 60));

        text9.setBackground(new java.awt.Color(255, 255, 255));
        text9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text9.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoMusical.add(text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 220, 30));

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 102));
        jLabel35.setText("Titulo");
        modificacionEventoMusical.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 70, 60));

        text10.setBackground(new java.awt.Color(255, 255, 255));
        text10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text10.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoMusical.add(text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 200, 30));

        jLabel36.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 102));
        jLabel36.setText("Descripcion");
        modificacionEventoMusical.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 60));

        text11.setBackground(new java.awt.Color(255, 255, 255));
        text11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text11.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoMusical.add(text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 210, 30));

        jLabel37.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 102));
        jLabel37.setText("Fecha");
        modificacionEventoMusical.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 70, 60));
        modificacionEventoMusical.add(datezzz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 210, 40));

        jLabel38.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 102));
        jLabel38.setText("Monto");
        modificacionEventoMusical.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 90, 60));

        text12.setBackground(new java.awt.Color(255, 255, 255));
        text12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text12.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoMusical.add(text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 210, 30));

        jButton7.setBackground(new java.awt.Color(0, 0, 102));
        jButton7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(153, 255, 255));
        jButton7.setText("Siguiente");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        modificacionEventoMusical.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 210, 80));

        jButton8.setBackground(new java.awt.Color(102, 0, 0));
        jButton8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 153, 153));
        jButton8.setText("Regresar al menu");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        modificacionEventoMusical.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 210, 80));

        getContentPane().add(modificacionEventoMusical, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 450));

        modificacionEventoDeportivo.setBackground(new java.awt.Color(153, 255, 255));
        modificacionEventoDeportivo.setMinimumSize(new java.awt.Dimension(480, 80));
        modificacionEventoDeportivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Descripcion");
        modificacionEventoDeportivo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 60));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Modificar Evento Deportivo");
        modificacionEventoDeportivo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 460, 60));

        text1.setBackground(new java.awt.Color(255, 255, 255));
        text1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text1.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoDeportivo.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 240, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Cantidad de Personas");
        modificacionEventoDeportivo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 250, 60));

        text2.setBackground(new java.awt.Color(255, 255, 255));
        text2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text2.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoDeportivo.add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 220, 30));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Codigo unico");
        modificacionEventoDeportivo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 60));

        text3.setBackground(new java.awt.Color(255, 255, 255));
        text3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text3.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoDeportivo.add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 200, 30));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Equipo 2");
        modificacionEventoDeportivo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 100, 60));

        text4.setBackground(new java.awt.Color(255, 255, 255));
        text4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text4.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoDeportivo.add(text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 210, 30));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Titulo");
        modificacionEventoDeportivo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 70, 60));
        modificacionEventoDeportivo.add(datezzz, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 210, 40));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Fecha");
        modificacionEventoDeportivo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 70, 60));

        text5.setBackground(new java.awt.Color(255, 255, 255));
        text5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text5.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoDeportivo.add(text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 210, 30));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Monto");
        modificacionEventoDeportivo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 90, 60));

        text6.setBackground(new java.awt.Color(255, 255, 255));
        text6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text6.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoDeportivo.add(text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 210, 30));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Equipo 1");
        modificacionEventoDeportivo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 100, 60));

        text7.setBackground(new java.awt.Color(255, 255, 255));
        text7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        text7.setForeground(new java.awt.Color(0, 0, 0));
        modificacionEventoDeportivo.add(text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 210, 30));

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 255, 255));
        jButton3.setText("Siguiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        modificacionEventoDeportivo.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 210, 80));

        jButton5.setBackground(new java.awt.Color(102, 0, 0));
        jButton5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 153, 153));
        jButton5.setText("Regresar al menu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        modificacionEventoDeportivo.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 210, 80));

        getContentPane().add(modificacionEventoDeportivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 530));

        bandazzz.setBackground(new java.awt.Color(153, 255, 255));
        bandazzz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("Integrante 3");
        bandazzz.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, 70));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 102));
        jLabel21.setText("Equipo Musical");
        bandazzz.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 340, 70));

        integrante2.setBackground(new java.awt.Color(255, 255, 255));
        integrante2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        integrante2.setForeground(new java.awt.Color(0, 0, 0));
        bandazzz.add(integrante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 150, 30));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 102));
        jLabel24.setText("Rol");
        bandazzz.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 40, 40));

        integrante1.setBackground(new java.awt.Color(255, 255, 255));
        integrante1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        integrante1.setForeground(new java.awt.Color(0, 0, 0));
        bandazzz.add(integrante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 150, 30));

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 102));
        jLabel26.setText("Integrante 2");
        bandazzz.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, 70));

        integrante3.setBackground(new java.awt.Color(255, 255, 255));
        integrante3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        integrante3.setForeground(new java.awt.Color(0, 0, 0));
        bandazzz.add(integrante3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 150, 30));

        jButton6.setBackground(new java.awt.Color(0, 0, 102));
        jButton6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 255, 255));
        jButton6.setText("Siguiente");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        bandazzz.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 180, 60));

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 102));
        jLabel27.setText("Integrante 1");
        bandazzz.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 70));

        rol1.setBackground(new java.awt.Color(255, 255, 255));
        rol1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        rol1.setForeground(new java.awt.Color(0, 0, 0));
        bandazzz.add(rol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 170, 30));

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 102));
        jLabel30.setText("Rol");
        bandazzz.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 40, 40));

        rol2.setBackground(new java.awt.Color(255, 255, 255));
        rol2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        rol2.setForeground(new java.awt.Color(0, 0, 0));
        bandazzz.add(rol2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 170, 30));

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 102));
        jLabel31.setText("Rol");
        bandazzz.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 40, 40));

        rol3.setBackground(new java.awt.Color(255, 255, 255));
        rol3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        rol3.setForeground(new java.awt.Color(0, 0, 0));
        bandazzz.add(rol3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 170, 30));

        getContentPane().add(bandazzz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 540));

        equipozzz.setBackground(new java.awt.Color(153, 255, 255));
        equipozzz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Equipo 2");
        equipozzz.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 160, 60));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Jugador 5");
        equipozzz.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, 30));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Equipo 1");
        equipozzz.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 160, 60));

        j1.setBackground(new java.awt.Color(255, 255, 255));
        j1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        j1.setForeground(new java.awt.Color(0, 0, 0));
        equipozzz.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, -1));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("Jugador 2");
        equipozzz.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 100, 30));

        j2.setBackground(new java.awt.Color(255, 255, 255));
        j2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        j2.setForeground(new java.awt.Color(0, 0, 0));
        equipozzz.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 160, -1));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Jugador 2");
        equipozzz.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 30));

        j3.setBackground(new java.awt.Color(255, 255, 255));
        j3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        j3.setForeground(new java.awt.Color(0, 0, 0));
        equipozzz.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 160, -1));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("Jugador 3");
        equipozzz.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 30));

        j4.setBackground(new java.awt.Color(255, 255, 255));
        j4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        j4.setForeground(new java.awt.Color(0, 0, 0));
        equipozzz.add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 160, -1));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("Jugador 4");
        equipozzz.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, 30));

        j5.setBackground(new java.awt.Color(255, 255, 255));
        j5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        j5.setForeground(new java.awt.Color(0, 0, 0));
        equipozzz.add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 160, -1));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("Jugador 5");
        equipozzz.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, 30));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 102));
        jLabel22.setText("Jugador 1");
        equipozzz.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, 30));

        j6.setBackground(new java.awt.Color(255, 255, 255));
        j6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        j6.setForeground(new java.awt.Color(0, 0, 0));
        equipozzz.add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 160, -1));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 102));
        jLabel23.setText("Jugador 1");
        equipozzz.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 80, 30));

        j7.setBackground(new java.awt.Color(255, 255, 255));
        j7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        j7.setForeground(new java.awt.Color(0, 0, 0));
        equipozzz.add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 160, -1));

        j8.setBackground(new java.awt.Color(255, 255, 255));
        j8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        j8.setForeground(new java.awt.Color(0, 0, 0));
        equipozzz.add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 160, -1));

        j9.setBackground(new java.awt.Color(255, 255, 255));
        j9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        j9.setForeground(new java.awt.Color(0, 0, 0));
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9ActionPerformed(evt);
            }
        });
        equipozzz.add(j9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 160, -1));

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("Jugador 3");
        equipozzz.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 90, 30));

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 102));
        jLabel28.setText("Jugador 5");
        equipozzz.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 90, 30));

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 102));
        jLabel29.setText("Jugador 4");
        equipozzz.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 90, 30));

        j10.setBackground(new java.awt.Color(255, 255, 255));
        j10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        j10.setForeground(new java.awt.Color(0, 0, 0));
        j10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j10ActionPerformed(evt);
            }
        });
        equipozzz.add(j10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 160, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 102));
        jButton4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 255, 255));
        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        equipozzz.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 170, 60));

        getContentPane().add(equipozzz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 530));

        personasConvertidas.setBackground(new java.awt.Color(153, 255, 255));
        personasConvertidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 102));
        jLabel39.setText("Personas Convertidas");
        personasConvertidas.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 360, 70));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        personasConvertidas.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 330, 50));

        jButton9.setBackground(new java.awt.Color(0, 0, 102));
        jButton9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jButton9.setForeground(new java.awt.Color(153, 255, 255));
        jButton9.setText("Siguiente");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        personasConvertidas.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 270, 90));

        getContentPane().add(personasConvertidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 680, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int codez;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        codez =Integer.parseInt(codigoAEditar.getText());
        if(codez<0){
            JOptionPane.showMessageDialog(this, "Numero ingresadp invalido! ");
        }else{
            if(Eventos.buscar(codez, 0)!=null){
            solicitudCode.setVisible(false);
            if(Eventos.buscar(codez, 0).tipoEvento.equalsIgnoreCase("deportivo")){
                deportes ED = (deportes) Eventos.buscar(codez,0);
                if(ED.tipoEvento.equalsIgnoreCase("deportivo")){
                    equipozzz.setVisible(true);
                }
            }else if(Eventos.buscar(codez, 0).tipoEvento.equalsIgnoreCase("musical")){
                musical EM =(musical)Eventos.buscar(codez, 0);
                if(EM.tipoEvento.equalsIgnoreCase("musical")){
                    bandazzz.setVisible(true);
                }
            }else{
                religioso ER =(religioso)Eventos.buscar(codez, 0);
                if(ER.tipoEvento.equalsIgnoreCase("religioso")){
                    personasConvertidas.setVisible(true);
                }
            }
            
            
            
            
        }else{
            JOptionPane.showMessageDialog(this, "Codigo no encontrado! ");
        }
        }
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int people=Integer.parseInt(text1.getText());
        int code=Integer.parseInt(text2.getText());
        double montoZ=Double.parseDouble(text5.getText());
        
        if(text1.getText().isEmpty() || text2.getText().isEmpty() || text3.getText().isEmpty() || text4.getText().isEmpty() || text5.getText().isEmpty() || text6.getText().isEmpty() || text7.getText().isEmpty() || datezzz.getDate()==null){
            JOptionPane.showMessageDialog(this,"Favor rellenar todas las casillas! ");
        }else if(people>20000 || people<0){
            JOptionPane.showMessageDialog(this, "Cantidad de personas invalido! ");
        }else if(Eventos.buscar(code, 0)!=null){
            JOptionPane.showMessageDialog(this,"Codigo existente! ");
        }else{
            
            Calendar date = Calendar.getInstance();
        
            int day = datezzz.getCalendar().get(Calendar.DAY_OF_MONTH);
            int month = datezzz.getCalendar().get(Calendar.MONTH);
            int year = datezzz.getCalendar().get(Calendar.YEAR);
            
            date.set(Calendar.YEAR, year);
            date.set(Calendar.MONTH, month);
            date.set(Calendar.DAY_OF_MONTH, day);
            
            deportes sport = (deportes) Eventos.buscar(codez,0);
            
            sport.setCreador(Login.logged);
            sport.setCantPersonas(people);
            sport.setCodigo(code);
            sport.setTitulo(text3.getText());
            sport.setDescripcion(text4.getText());
            sport.setFecha(date);
            sport.setMonto(montoZ);
            sport.setTeam1(text6.getText());
            sport.setTeam2(text7.getText());
            JOptionPane.showMessageDialog(this, "Se ha editado el evento correctamente! ");
            AdministracionEventos ad = new AdministracionEventos();
            ad.setVisible(true);
            ad.setLocationRelativeTo(null);
            this.setVisible(false);
//            System.out.println(sport.getCodigo());
//            System.out.println(sport.creador);
//            System.out.println(sport.tipoDeporte);
//            
//            for(String[] search:deportes.teams1){
//               for(int x=0;x<search.length;x++){
//                   System.out.println(search[x]);
//               }
//            }
//            System.out.println(sport.estado);
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void j9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j9ActionPerformed

    private void j10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdministracionEventos admin = new AdministracionEventos();
        admin.setVisible(true);
        admin.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(j1.getText().isEmpty() || j2.getText().isEmpty() || j3.getText().isEmpty() || j4.getText().isEmpty() || j5.getText().isEmpty() || j6.getText().isEmpty() || j7.getText().isEmpty() || j8.getText().isEmpty() || j9.getText().isEmpty() || j10.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Rellenar todas las casillas! ");
        }else{
            
            String equipo[]={j1.getText(),j2.getText(),j3.getText(),j4.getText(),j5.getText()};
            String equipo2[]={j6.getText(),j7.getText(),j8.getText(),j9.getText(),j10.getText()};
            
            deportes.teams1.add(Eventos.posicion(codez, 0), equipo);
            deportes.teams2.add(Eventos.posicion(codez, 0),equipo2);
            
            modificacionEventoDeportivo.setVisible(true);
            equipozzz.setVisible(false);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AdministracionEventos ad = new AdministracionEventos();
        ad.setVisible(true);
        ad.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String integranteUno=rol1.getText()+": "+integrante1.getText();
        String integranteDos=rol2.getText()+": "+integrante2.getText();
        String integranteTres=rol3.getText()+": "+integrante3.getText();
        
        String[] banda={integranteUno,integranteDos,integranteTres};
        
        musical.banda.add(banda);
        
        modificacionEventoMusical.setVisible(true);
        bandazzz.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int people=Integer.parseInt(text8.getText());
        int code=Integer.parseInt(text9.getText());
        double montoZ=Double.parseDouble(text12.getText());
        
        if(text8.getText().isEmpty() || text9.getText().isEmpty() || text10.getText().isEmpty() || text11.getText().isEmpty() || text12.getText().isEmpty() || datezzz1.getDate()==null){
            JOptionPane.showMessageDialog(this,"Favor rellenar todas las casillas! ");
        }else if(people>25000 || people<0){
            JOptionPane.showMessageDialog(this, "Cantidad de personas invalido! ");
        }else if(Eventos.buscar(code, 0)!=null){
            JOptionPane.showMessageDialog(this,"Codigo existente! ");
        }else{
            Calendar date = Calendar.getInstance();
        
            int day = datezzz1.getCalendar().get(Calendar.DAY_OF_MONTH);
            int month = datezzz1.getCalendar().get(Calendar.MONTH);
            int year = datezzz1.getCalendar().get(Calendar.YEAR);
            
            date.set(Calendar.YEAR, year);
            date.set(Calendar.MONTH, month);
            date.set(Calendar.DAY_OF_MONTH, day);
            
            musical music = (musical) Eventos.buscar(codez,0);
            
            music.setCreador(Login.logged);
            music.setCantPersonas(people);
            music.setCodigo(code);
            music.setTitulo(text10.getText());
            music.setDescripcion(text11.getText());
            music.setFecha(date);
            music.setMonto(montoZ);
            JOptionPane.showMessageDialog(this, "Se ha editado el evento correctamente! ");
            AdministracionEventos ad = new AdministracionEventos();
            ad.setVisible(true);
            ad.setLocationRelativeTo(null);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        AdministracionEventos ad = new AdministracionEventos();
        ad.setVisible(true);
        ad.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int convertidas=Integer.parseInt(jTextField1.getText());
        if(jTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Favor rellenar todas las casillas! ");
        }else{
            religioso.converted.add(convertidas);
            modificacionEventoReligioso.setVisible(true);
            personasConvertidas.setVisible(false);
        }
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int people=Integer.parseInt(text13.getText());
        int code=Integer.parseInt(text14.getText());
        
        if(text13.getText().isEmpty() || text14.getText().isEmpty() || text15.getText().isEmpty() || text16.getText().isEmpty() || datezzz2.getDate()==null){
            JOptionPane.showMessageDialog(this,"Favor rellenar todas las casillas! ");
        }else if(people>30000 || people<0){
            JOptionPane.showMessageDialog(this, "Cantidad de personas invalido! ");
        }else if(Eventos.buscar(code, 0)!=null){
            JOptionPane.showMessageDialog(this,"Codigo existente! ");
        }else{
            Calendar date = Calendar.getInstance();
        
            int day = datezzz2.getCalendar().get(Calendar.DAY_OF_MONTH);
            int month = datezzz2.getCalendar().get(Calendar.MONTH);
            int year = datezzz2.getCalendar().get(Calendar.YEAR);
            
            date.set(Calendar.YEAR, year);
            date.set(Calendar.MONTH, month);
            date.set(Calendar.DAY_OF_MONTH, day);
            
            religioso R = (religioso) Eventos.buscar(codez,0);
            
            R.setCreador(Login.logged);
            R.setCantPersonas(people);
            R.setCodigo(code);
            R.setTitulo(text10.getText());
            R.setDescripcion(text11.getText());
            R.setFecha(date);
            JOptionPane.showMessageDialog(this, "Se ha editado el evento correctamente! ");
            AdministracionEventos ad = new AdministracionEventos();
            ad.setVisible(true);
            ad.setLocationRelativeTo(null);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        AdministracionEventos ad = new AdministracionEventos();
        ad.setVisible(true);
        ad.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editarEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bandazzz;
    private javax.swing.JTextField codigoAEditar;
    private com.toedter.calendar.JDateChooser datezzz;
    private com.toedter.calendar.JDateChooser datezzz1;
    private com.toedter.calendar.JDateChooser datezzz2;
    private javax.swing.JPanel equipozzz;
    private javax.swing.JTextField integrante1;
    private javax.swing.JTextField integrante2;
    private javax.swing.JTextField integrante3;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j10;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j6;
    private javax.swing.JTextField j7;
    private javax.swing.JTextField j8;
    private javax.swing.JTextField j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel modificacionEventoDeportivo;
    private javax.swing.JPanel modificacionEventoMusical;
    private javax.swing.JPanel modificacionEventoReligioso;
    private javax.swing.JPanel personasConvertidas;
    private javax.swing.JTextField rol1;
    private javax.swing.JTextField rol2;
    private javax.swing.JTextField rol3;
    private javax.swing.JPanel solicitudCode;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text10;
    private javax.swing.JTextField text11;
    private javax.swing.JTextField text12;
    private javax.swing.JTextField text13;
    private javax.swing.JTextField text14;
    private javax.swing.JTextField text15;
    private javax.swing.JTextField text16;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text6;
    private javax.swing.JTextField text7;
    private javax.swing.JTextField text8;
    private javax.swing.JTextField text9;
    // End of variables declaration//GEN-END:variables
}
