/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package andresmartinez_javaticket;

import javax.swing.JOptionPane;
import java.util.Calendar;
/**
 *
 * @author andre
 */
public class verEvento extends javax.swing.JFrame {

    /**
     * Creates new form verEvento
     */
    public verEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codeee = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Codigo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 90, 50));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Ver Evento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 210, 50));

        codeee.setBackground(new java.awt.Color(255, 255, 255));
        codeee.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        codeee.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(codeee, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 230, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 204, 255));
        jButton1.setText("Ver Evento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 210, 90));

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 153));
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 180, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdministracionEventos a = new AdministracionEventos();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int codigo=Integer.parseInt(codeee.getText());
        if(codeee.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Favor rellenar la casilla! ");
        }else if(codigo>=0){
            
            
            Eventos e =(Eventos) Eventos.buscar(codigo,0);
            if(e.tipoEvento.equalsIgnoreCase("deportivo")){
                deportes sport =(deportes) Eventos.buscar(codigo, 0);
                int dia = sport.fecha.get(Calendar.DAY_OF_MONTH);
                int mes = sport.fecha.get(Calendar.MONTH)+1;
                int ano = sport.fecha.get(Calendar.YEAR);
                String pane = "Creador: "+sport.creador+"\nCodigo: "+sport.codigo+"\nTitulo: "+sport.titulo+"\nCant. de Personas: "+sport.cantPersonas+"\nDescripcion: "+sport.descripcion+"\nTipo de Evento: "+sport.tipoEvento+"\nMonto: "+sport.monto+"\nFecha: "+dia+" / "+mes+" / "+ano+"\nDeporte: "+sport.tipoDeporte+"\nEquipo 1: "+sport.Team1+"\nEquipo 2: "+sport.Team2+"\nEstado: "+sport.estado;
                JOptionPane.showMessageDialog(this,pane );
            }else if(e.tipoEvento.equalsIgnoreCase("musical")){
                musical music =(musical) Eventos.buscar(codigo, 0);
                int dia = music.fecha.get(Calendar.DAY_OF_MONTH);
                int mes = music.fecha.get(Calendar.MONTH)+1;
                int ano = music.fecha.get(Calendar.YEAR);
                String pane="Creador: "+music.creador+"\nCodigo: "+music.codigo+"\nTitulo: "+music.titulo+"\nCant. de Personas: "+music.cantPersonas+"\nDescripcion: "+music.descripcion+"\nTipo de Evento: "+music.tipoEvento+"\nMonto: "+music.monto+"\nFecha: "+dia+" / "+mes+" / "+ano+"\nGenero Musical: "+music.tipoMusica+"\nEstado: "+music.estado;                 
                JOptionPane.showMessageDialog(this,pane );
            }else{
                religioso religion =(religioso) Eventos.buscar(codigo, 0);
                int dia = religion.fecha.get(Calendar.DAY_OF_MONTH);
                int mes = religion.fecha.get(Calendar.MONTH)+1;
                int ano = religion.fecha.get(Calendar.YEAR);
                String pane="Creador: "+religion.creador+"\nCodigo: "+religion.codigo+"\nTitulo: "+religion.titulo+"\nCant. de Personas: "+religion.cantPersonas+"\nDescripcion: "+religion.descripcion+"\nTipo de Evento: "+religion.tipoEvento+"\nMonto: "+religion.monto+"\nFecha: "+dia+" / "+mes+" / "+ano+"\nEstado: "+religion.estado;
                JOptionPane.showMessageDialog(this,pane );
            }
            
        }else{
            JOptionPane.showMessageDialog(this,"Numero ingresado invalido! ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codeee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
